
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Bloodstorageinfo extends javax.swing.JFrame {

    /**
     * Creates new form Bloodstorageinfo
     */
    public Bloodstorageinfo() {
        initComponents();
         bloodgroup.setBackground(new Color(0,0,0,0));
          datetaken.setBackground(new Color(0,0,0,0));
           datesupplied.setBackground(new Color(0,0,0,0));
           did.setBackground(new Color(0,0,0,0));
            insertbloodinfo.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bloodgroup = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        insertbloodinfo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        datetaken = new com.toedter.calendar.JDateChooser();
        datesupplied = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\3-1\\LAB\\Database Lab\\blood-bank.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Blood Group");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, 30));

        bloodgroup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(bloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Date Taken");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Date Supplied");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 160, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 170, 10));

        insertbloodinfo.setIcon(new javax.swing.ImageIcon("D:\\3-1\\LAB\\Database Lab\\add-box.png")); // NOI18N
        insertbloodinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbloodinfoActionPerformed(evt);
            }
        });
        jPanel1.add(insertbloodinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 60, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Donor ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 80, 30));

        did.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 180, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 302, 190, 10));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 333, -1, 30));

        datetaken.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(datetaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 144, 160, -1));

        datesupplied.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datesupplied.setToolTipText("");
        jPanel1.add(datesupplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 333, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertbloodinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbloodinfoActionPerformed
        // TODO add your handling code here:
        if(((JTextField)datesupplied.getDateEditor().getUiComponent()).getText().isEmpty())
       {             
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=Bloodbank;user=Sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "Insert into BLOODINFO"
                    +"(BLOOD_GROUP,DATE_TAKEN,DATE_SUPPLIED,DONOR_ID)"
                    +"values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,bloodgroup.getText());
              pst.setString(2,((JTextField)datetaken.getDateEditor().getUiComponent()).getText());
              pst.setString(3,((JTextField)datesupplied.getDateEditor().getUiComponent()).getText());
               pst.setString(4,did.getText( ));
             // pst.setString(3,((JTextField)datesupplied.getDateEditor().getUiComponent()).getText());
             
            
           // ResultSet rs = 
            pst.executeUpdate(); 
        
               JOptionPane.showMessageDialog(null, "Successfully Registered");
               //InsertFrame.Succes field= new  InsertFrame.Succes();
              // field.setVisible(true);
               //setVisible(false);
                ((JTextField) datetaken.getDateEditor().getUiComponent()).setText("");
                bloodgroup.setText("");
                 //((JTextField)datesupplied.getDateEditor().getUiComponent()).setText("");
                did.setText("");
                //orderbgroup.setText("");
               
       
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
        }  
         else
         {
                 try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=Bloodbank;user=Sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "Insert into BLOODINFO"
                    +"(BLOOD_GROUP,DATE_TAKEN,DATE_SUPPLIED,DONOR_ID)"
                    +"values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
         
            pst.setString(1,bloodgroup.getText());
              pst.setString(2,((JTextField)datetaken.getDateEditor().getUiComponent()).getText());
              pst.setString(3,((JTextField)datesupplied.getDateEditor().getUiComponent()).getText());
              pst.setString(4,did.getText());
             
           // ResultSet rs = 
            pst.executeUpdate(); 
        
               JOptionPane.showMessageDialog(null, "Successfully Registered");
               //InsertFrame.Succes field= new  InsertFrame.Succes();
              // field.setVisible(true);
               //setVisible(false);
                ((JTextField) datetaken.getDateEditor().getUiComponent()).setText("");
                bloodgroup.setText("");
                 ((JTextField)datesupplied.getDateEditor().getUiComponent()).setText("");
                did.setText("");
                //orderbgroup.setText("");
               
       
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
             
             
         }
    }//GEN-LAST:event_insertbloodinfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Homepage gohome=new Homepage();
        gohome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bloodinfohome bhome=new bloodinfohome();
        bhome.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bloodstorageinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bloodstorageinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bloodstorageinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bloodstorageinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bloodstorageinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodgroup;
    private com.toedter.calendar.JDateChooser datesupplied;
    private com.toedter.calendar.JDateChooser datetaken;
    private javax.swing.JTextField did;
    private javax.swing.JButton insertbloodinfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
