/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS*
 */
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class LOGIN extends javax.swing.JFrame {
    Connection con;

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        con=ConnectMSSQL.connectDB();
        
        //BankId.setBackground(new Color(0,0,0,0));
        // bankname.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        managerid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        managerpassword = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jlabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managerid.setBackground(new java.awt.Color(204, 204, 204));
        managerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageridActionPerformed(evt);
            }
        });
        jPanel1.add(managerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Manager ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, 30));

        managerpassword.setBackground(new java.awt.Color(204, 204, 204));
        managerpassword.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(managerpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 170, 30));

        login.setIcon(new javax.swing.ImageIcon("D:\\3-1\\LAB\\Database Lab\\loginimg.jpg")); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 90, 30));

        jlabel4.setBackground(new java.awt.Color(51, 255, 51));
        jlabel4.setForeground(new java.awt.Color(51, 0, 204));
        jlabel4.setIcon(new javax.swing.ImageIcon("D:\\3-1\\LAB\\Database Lab\\bloodbank.png")); // NOI18N
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 610, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageridActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Select * from MANAGER where MANAGER_ID =? and PASSWORD = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, managerid.getText());
            pst.setString(2,managerpassword.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                //JOptionPane.showMessageDialog(null, "Username and Password Matched");
               //Succes field= new Succes();
               //field.setVisible(true);
               setVisible(false);
               Homepage home=new Homepage();
               home.setVisible(true);
               
                managerid.setText("");
                managerpassword.setText("");
               
            }
            else{
                JOptionPane.showMessageDialog(null, "Username and password not Correct");
                managerid.setText("");
                managerpassword.setText("");
            }
            con.close();
        }
         catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JButton login;
    private javax.swing.JTextField managerid;
    private javax.swing.JTextField managerpassword;
    // End of variables declaration//GEN-END:variables
 private static class Succes {

        public Succes() {
        }

        private void setVisible(boolean b) {
            
        }
    }

}
