
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class updatebloodinfo extends javax.swing.JFrame {

    /**
     * Creates new form updatebloodinfo
     */
    public updatebloodinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        updatedatetaken = new javax.swing.JButton();
        updatedatesupplied = new javax.swing.JButton();
        bdatetaken = new com.toedter.calendar.JDateChooser();
        ddatesupplied = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date Taken");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date Supplied");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 160, 90, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Donor ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, 20));
        getContentPane().add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 90, -1));

        updatedatetaken.setText("Update");
        updatedatetaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedatetakenActionPerformed(evt);
            }
        });
        getContentPane().add(updatedatetaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        updatedatesupplied.setText("Update");
        updatedatesupplied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedatesuppliedActionPerformed(evt);
            }
        });
        getContentPane().add(updatedatesupplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));
        getContentPane().add(bdatetaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));
        getContentPane().add(ddatesupplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jButton1.setText("Homepage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 273, -1, 40));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\3-1\\LAB\\Database Lab\\bloodbank.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -6, 630, 370));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatedatetakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedatetakenActionPerformed
        // TODO add your handling code here:
          try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url="jdbc:sqlserver://localhost:1433;databaseName=Bloodbank;user=sa;password=123456";
           Connection con = DriverManager.getConnection(url);
            String sql = "Update BLOODINFO set  DATE_TAKEN=? where DONOR_ID=?";
            
            PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1,((JTextField)bdatetaken.getDateEditor().getUiComponent()).getText());
            pst.setString(2,did.getText());
        
            pst.executeUpdate();
        
               JOptionPane.showMessageDialog(null, "Successfully Updated");
               //InsertFrame.Succes field= new  InsertFrame.Succes();
               //field.setVisible(true);
             
               ((JTextField)bdatetaken.getDateEditor().getUiComponent()).setText("");
                did.setText("");
               
       
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
        
    }//GEN-LAST:event_updatedatetakenActionPerformed

    private void updatedatesuppliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedatesuppliedActionPerformed
        // TODO add your handling code here:
          try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url="jdbc:sqlserver://localhost:1433;databaseName=Bloodbank;user=sa;password=123456";
           Connection con = DriverManager.getConnection(url);
            String sql = "Update BLOODINFO set  DATE_SUPPLIED=? where DONOR_ID=?";
            
            PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1,((JTextField)ddatesupplied.getDateEditor().getUiComponent()).getText());
            pst.setString(2,did.getText());
        
            pst.executeUpdate();
        
               JOptionPane.showMessageDialog(null, "Successfully Updated");
               //InsertFrame.Succes field= new  InsertFrame.Succes();
               //field.setVisible(true);
             
                //raddress.setText("");
                //rid.setText("");
               
       
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_updatedatesuppliedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Homepage gohome=new Homepage();
        gohome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bloodinfohome bhome=new bloodinfohome();
        bhome.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatebloodinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatebloodinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatebloodinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatebloodinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatebloodinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bdatetaken;
    private com.toedter.calendar.JDateChooser ddatesupplied;
    private javax.swing.JTextField did;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updatedatesupplied;
    private javax.swing.JButton updatedatetaken;
    // End of variables declaration//GEN-END:variables
}
